name: "Pull Request"

on:
  pull_request:
    branches:
      - main
    paths:
      - ".github/workflows/pull-request.yml"
      - "**/*.go"
      - "go.mod"
      - "go.sum"

jobs:
  setup:
    runs-on: ubuntu-latest
    name: Setup

    steps:
      - uses: actions/checkout@v4

      - name: Setup environment
        uses: ./.github/actions/setup-env

  build:
    needs: setup
    runs-on: ubuntu-latest
    name: Build

    steps:
      - uses: actions/checkout@v4

      - name: Setup environment
        uses: ./.github/actions/setup-env

      - name: Build
        run: |
          go build examples/basic/main.go

  lint:
    needs: setup
    runs-on: ubuntu-latest
    name: Analyze

    steps:
      - uses: actions/checkout@v4

      - name: Setup environment
        uses: ./.github/actions/setup-env

      - name: Lint
        uses: golangci/golangci-lint-action@v6
